services:
  lego-migrate:
    container_name: lego-migrate
    image: goacme/lego:v5.3.1
    volumes:
      - /etc/letsencrypt/lego_cert_store:/certs
    command: "migrate --path=\"/certs\""

  lego-run:
    container_name: lego-run
    image: goacme/lego:v5.3.1
    environment:
      - INFOMANIAK_ACCESS_TOKEN=$INFOMANIAK_ACCESS_TOKEN
    volumes:
      - /etc/letsencrypt/lego_cert_store:/certs
    command: "run
             --accept-tos
             --email=\"simon.bowie@protonmail.com\"
             --dns=\"infomaniak\"
             --path=\"/certs\"
             --domains=\"simonxix.com\"
             --domains=\"*.simonxix.com\""

