version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /srv/www/wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/www/wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /home/simonxix/www:/var/www/testing
    networks:
      - app-network

  sandstorm:
    depends_on: 
      - webserver
    image: buildpack-deps
    restart: unless-stopped
    container_name: sandstorm
    volumes:
      - /opt/sandstorm:/opt/sandstorm/
    ports:
      - "0.0.0.0:6080:6080"
    expose:
      - "443"
    privileged: true
    networks:
      - app-network
    entrypoint: 
      bash -c 'useradd --system --user-group sandstorm && /opt/sandstorm/sandstorm start && tail -f /opt/sandstorm/var/log/sandstorm.log & sleep infinity'

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
