version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /srv/www/wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
      - goaccess
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "37890:37890"
    volumes:
      # WordPress
      - /srv/www/wordpress:/var/www/html
      # Nginx configuration files and SSL certs/keys
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/ssl:/etc/nginx/ssl
      # Other websites
      - /home/simonxix/websites:/var/www/
      # GoAccess
      - ./goaccess/html:/srv/report
      - /home/simonxix/logs/nginx:/var/log/nginx
      - ./goaccess/data/access.conf:/etc/nginx/access.conf
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /srv/www/wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email simonxix@simonxix.com --agree-tos --no-eff-email --force-renewal -d simonxix.com -d www.simonxix.com

  sandstorm:
    depends_on: 
      - webserver
    image: buildpack-deps
    restart: unless-stopped
    container_name: sandstorm
    volumes:
      - /opt/sandstorm:/opt/sandstorm
      - /home/simonxix/docker/sandstorm_ssl:/home/sandstorm/bin
      - /etc/nginx/ssl:/etc/nginx/ssl
    expose:
      - "443"
    privileged: true
    networks:
      - app-network
    entrypoint: 
      bash -c 'useradd --system --user-group sandstorm && /opt/sandstorm/sandstorm start && tail -f /opt/sandstorm/var/log/sandstorm.log & sleep infinity'

  php:
    container_name: php
    image: php:8.0-fpm
    env_file:
      - /home/simonxix/websites/politics_of_patents_search/config.env
    volumes:
      - /home/simonxix/websites:/var/www
    networks:
      - app-network

  solr:
    container_name: solr
    image: solr:latest
    ports:
      - '8983:8983'
    volumes:
      - solrdata:/var/solr
    networks:
      - app-network

  goaccess:
    # build and Nginx config from https://github.com/icamys/docker-goaccess-nginx
    build:
       context: ./goaccess
       dockerfile: Dockerfile
       args:
          ALPINE_VERSION: 3.10.2
    restart: unless-stopped
    container_name: goaccess
    expose:
       - "7890"
    volumes:
       - ./goaccess/data:/srv/data
       - ./goaccess/html:/srv/report
       - /home/simonxix/logs/nginx:/var/log/nginx/
       - ./goaccess/data/database:/tmp
    networks:
       - app-network

volumes:
  dbdata:
  solrdata:

networks:
  app-network:
    driver: bridge
