services:
  webserver:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
      - 37890:37890
    volumes:
      # Nginx configuration files
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf:/etc/nginx/conf.d
      # SSL certificates/keys
      - /etc/letsencrypt/lego_cert_store:/certs    
      - /etc/letsencrypt:/etc/letsencrypt #temporary: remove in production  
      # Sandstorm SSL
      - /home/simonxix/docker/sandstorm/sandstorm_ssl:/etc/nginx/ssl 
      # Static websites
      - /home/simonxix/static_websites:/var/www/
      # PHP websites
      - /home/simonxix/php_websites:/var/php/
      # WordPress
      - ../wordpress/wordpress_content:/var/wordpress
      # GoAccess
      - ../goaccess/html:/srv/report
      - /home/simonxix/logs/nginx:/var/log/nginx
      - ../goaccess/data/access.conf:/etc/nginx/access.conf
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
